



### DEPRECATED #####
### DEPRECATED #####
### DEPRECATED #####
### DEPRECATED #####
### USE hep_screen_v1.5 OR LATER FOR ALCATRAZ DATA ###




## this code makes the same product as the HEP_screening/code_data_files/hep_screen.R (a multi-sheet excel file that allows the manual screening of nest), but does so for the Alcatraz data we get from USGS
## Alcatraz requires a slightly-modified screening code because a couple key pieces of info that the main screening code relies on are not collected on Alcatraz (number of parents present and confidence in chick count). 
## also, the same visit info is not collected, so 
## the sheets created are:
## 1. The scoring sheet: Either 1 sheet, named 'nests' (for colonies with few nests or species), or a sheet for each species (for large and multi-species colonies) that is equivalent to the handwritten scoring sheet, plus some fields generated by the nest screening algorithm that serve as helpers for the manual screening; the user determines whether 1 or multiple sheets are generated. This sheet has the following fields:
# species code
# nest ID
# columns for each day the nest was checked showing the number of adults, status, number of chicks, and confidence in chick count
# 'focal' =  yes/no (1/0) for whether the nest meets the basic requirements for being focal
# 'focal fail' = yes/no (1/0) for whether a nested classified as focal failed
# 'fledged = yes/no (1/0) for nests likely to have fledged (reached min fledge age in either stage 4 or 5), 
# 'days_short_of_fledging' = for nests that didn't clearly fail but were observed innactive earlier than expected, the number of days from the last date it was observed active until the expected fledge date; 
# 'active_last_day' = yes/no (1/0) indicating if nest was still active on the last day it was checked
# 'max_stage' = maximum stage teh nest was observed in
# 'num_spp' = number of species assigned to this nest ID- helps find where observer might have been confused about which nest was which, or true species turnovers
# 'stg4_brood' = maximum confidently observed stage 4 brood size

## 2. peak_active: shows the date, julian date, and number of nests for the peak active date for each species

## 3. stg4: number of stage 4 nests of each brood size for each species

## 4. nest_num_stage: number of nests of each species in each stage on each date the colony was checked

## 5. num_active: total number of active nests for each species on each date the colony was checked
#--------------------

## As long as you are running this screening code from the Alcatraz R Project, the working directory will not need to be set (if you just opened the this and the pathway in the read_csv function will need to be changed depending on each user's computer). Once the packages are loaded and the colony and season info have been set, then everything down to 'RUN TO HERE FIRST' around line 415 can be run

## then the decision about how many scoring sheets to write can be made, and the final xls file can be written back to the server

#--------------------
## load the required packages
library(plyr)
library(tidyverse)
library(reshape2)
library(lubridate)
library(xlsx)
library(readxl)
library(hms)
#setwd("C:/Users/scott.jennings/Documents/HEP_screening/") # ACR

#-----------
#specify which colony and season you want to work with
col="Alcatraz" # this needs to match the site_name field in the code_data_files/sub_sites.csv file; if the colony you're working on doesn't have a site_name yet, you can create one that makes sense (a shorter version of the colony name, with no spaces for best use as a file name); be sure to add this new site_name to the sub_sites file.
col.code="70"
seas="2015"

#-----------
##importing the file created by the alcatraz.R file also part of this project

alcatraz_hep=read.csv("Alcatraz_ready4screening/alcatraz2015_4screening.csv") 

names(alcatraz_hep) <- tolower(names(alcatraz_hep))


#-----------
## data management
alcatraz_hep <- alcatraz_hep %>% 
  mutate(status = as.character(status),
         nest = as.character(nest), ## to allow non-numerical nest IDs
         date = ymd(as.character(date))) %>% 
  select(species = spp, everything(), -adults, -confidence)




## and make a few new fields
alcatraz_hep <- alcatraz_hep %>% 
  mutate(jdate = yday(date), # create Julian date
         md=paste(month(date), day(date), sep = "-"), # create a fiedld for Month-Day
         # this next one creates the field to be displayed in the nest Scoring Form
         # combining number of adults, stage, number of chicks, and a * if confidence was checked,
         # or just status and adults if the nest was called something other than active
         stg.age.chx=ifelse(status == "I", status,
                            ifelse(chicks > 0, paste(stage, "(", chick.age, ")/", chicks, sep=""), 
                                   paste(stage, "/", chicks, sep=""))))


#-----------
# this not needed for any subsequent code, but can see what species are in the current data
#spp_list=unique(hep$species)


#-----------
## for each visit, make table with the number of nests in each stage
## gets written to final xls
nest_num_stage = alcatraz_hep %>% 
  filter(status=="A") %>%
  group_by(species, date, stage) %>%	
  summarise(num_nests = length(nest)) %>% 
  spread(date, num_nests)
names(nest_num_stage) <- gsub("2017-","",names(nest_num_stage)) # remove year from the column names for better viewing in final xlsx sheets


#-----------
## make wide version of the number of nests of all status for each species on each visit	
## gets written to final xls
num_active_wide <- alcatraz_hep %>% 
  filter(status=="A") %>%
  group_by(species, date) %>%	
  summarise(num_active = length(nest))  %>%  
  spread(date, num_active) 
names(num_active_wide) <- gsub("2017-","",names(num_active_wide)) # remove year from the column names for better viewing in final xlsx sheets


#-----------
## determine the date with the peak number of active nests, and PEAKACTVNSTS
## gets written to final xls
peak_active <- alcatraz_hep %>% 
  filter(status=="A") %>%
  group_by(species, date) %>%	
  summarise(num_active = length(nest))  	%>%
  group_by(species) %>%
  filter(num_active==max(num_active)) %>%
  filter(date==min(date)) %>% 
  mutate(peak_active_jdate = yday(date)) %>% 
  select(species, peak_active_date = date, peak_active_jdate, PEAKACTVNSTS = num_active)


#-----------
## make the df used by the nest screening algorithm
make_nests4screening <- function(){
  
  # create df with the minimum fledging age and duration of incubation for each species
  sp_stats1=data.frame(species=c('BCNH', 'SNEG', 'CAEG', 'GREG', 'GBHE', 'DCCO'),
                       min_fl=as.numeric(c('15', '14', '14', '49', '56', NA)),
                       inc_dur=as.numeric(c('25', '22', '24', 	'28', '28', NA))
  )
  
  
  # make several fields that will be used for automated screening 
  # determine the latest date of observations for each species
  spp_max_jdate = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species) %>%
    summarise(spp_max_jdate = max(jdate)) 
  
  # create a df with the general species info (min_fl and inc_dur) and the colony-specific species info (peak_active and spp_max_jdate)
  spp_stats <- full_join(peak_active, spp_max_jdate) %>% 
    inner_join(., sp_stats1)
  
  # create unique list of each species+nest combo
  spp.nests2 = unique(alcatraz_hep[c("species", "nest")])
  
  # merge unique nest list with the species info
  spp.nests1 = full_join(spp.nests2, spp_stats)
  
  # ID nests that were assigned to more than 1 species
  multi_spp_nests = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(nest) %>%
    summarise(num_spp = n_distinct(species))	
  
  # determin the maximum stage each nest was observed in	
  max_stage = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    summarise(max_stage = max(stage)) 
  
  # determin the minimum stage each nest was observed in		
  min_stage = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    summarise(min_stage = min(stage)) 
  
  # determin the minimum stage each nest was observed with chick		
  min_stage_chx = alcatraz_hep %>% 
    filter(status == "A", stage>1) %>%
    group_by(species, nest) %>%	
    summarise(min_stage_chx = min(stage)) 
  
  # determin the latest date each nest was observed	
  latest_date = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    summarise(latest_date = max(jdate)) 
  
  # determin the earliest date each nest was observed	
  earliest_date = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    summarise(earliest_date = min(jdate)) 
  
  # determin the latest date each nest was observed in stage 1	
  latest_date_stage1 = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%
    filter(stage == 1) %>%
    summarise(latest_date_stage1 = max(jdate)) 
  
  # determin the latest date each nest was observed in stage 4 or later
  oldest_chick_age = alcatraz_hep %>% 
    filter(status == "A", !is.na(chick.age)) %>%
    group_by(species, nest) %>%
    summarise(oldest_chick_age = max(chick.age)) 
  
  # determin the earliest date each nest was observed in stage 1
  earliest_date_stage1 = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%
    filter(stage == 1) %>%
    summarise(earliest_date_stage1 = min(jdate))	
  
  # determin the earliest date each nest was observed with chicks (later than stage 1)
  earliest_date_chx = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%
    filter(chicks > 0) %>%
    summarise(earliest_date_chx = min(jdate))	
  
  # determin the stage 4 brood size of each nests (where knowable)
  stg4_brood = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    filter(stage == 4) %>%
    filter(jdate == max(jdate)) %>%
    select(species, nest, stg4_brood = chicks) 
  
  #determin the earliest stage a nest was observed in	
  earliest_stage = alcatraz_hep %>% 
    filter(status == "A") %>%
    group_by(species, nest) %>%	
    filter(jdate == min(jdate)) %>%
    select(species, nest, earliest_stage = stage) %>% 
    distinct()
  
  ## bind all those created objects
  nests1=join_all(list(spp.nests1, earliest_date_chx, earliest_stage, min_stage_chx, earliest_date_stage1, latest_date_stage1, oldest_chick_age, max_stage, latest_date, earliest_date, stg4_brood), type = 'full')
  nests=join_all(list(nests1, multi_spp_nests), type = 'full')
  
  
  
  return(nests)
}
nests4screening <- make_nests4screening()


#-----------
# make automated screening calculations
screened_nests <- nests4screening %>%  
  mutate(
    # was the nest still active on the last day of nest checks for this species?
    active_last_day = ifelse(latest_date==spp_max_jdate, 1, 0),
    #meets criteria for focal nest 
    focal = ifelse(# nest was observed active before peak colony size
      earliest_date <= peak_active_jdate &
        # nest was observed before hatching
        earliest_stage < 2 & 
        # nest actually reached incubation or brooding
        max_stage > 0 & 
        # nest was first observed during the first 2 weeks of incubation or earlier
        ((earliest_date <= round(earliest_date_chx - (inc_dur - 14), 0)) & min_stage_chx < 4 ), 1, 0),	   
    # | means or
    
    # did the nest reach the minimum fledging age
    fledged = ifelse(oldest_chick_age > min_fl, 1, 0),
    
    # was it a focal nest that failed?
    focal_fail = ifelse(focal == 1 & active_last_day == 0 & fledged == 0, 1, 0),  
    
    #count number of days short of fledging the nest was observed
    days_short_of_fledging = ifelse(fledged == 0, oldest_chick_age - min_fl, "")
  )


#-----------
# count focal fails detected on each visit
make_foc_fails <- function(){
  # first determin which dates each species was surveyed
  survey_dates= alcatraz_hep %>% 
    distinct(species,date) 
  
  # then determine the final day observed for each focal nest that failed
  focal_fail_dates=screened_nests %>% 
    filter(focal_fail==1) %>% 
    group_by(species, latest_date) %>%
    summarize(num_fails = length(nest)) %>% 
    mutate(date = (as.Date(paste(seas,"-01-01", sep="")) + latest_date)-1) #get date back from julian date
  # join 	
  zdates <- full_join(focal_fail_dates, survey_dates)
  # this finds the next day after the last day a failed focal nest was observed active, which is the first day it was observed failed,
  # then makes it into wide format for output to the xls
  focal_fail_dates_wide <- zdates %>%
    arrange(species, date) %>% 
    mutate(next_date = lead(date),
           next_md = paste(month(next_date), day(next_date), sep="-"),
           next_md = ifelse(next_md=="NA-NA", "", next_md)) %>% 
    select(species, num_fails, next_md) %>% 
    filter(num_fails>0) %>% 
    spread(next_md, num_fails)
  return(focal_fail_dates_wide)
}
focal_fail_dates_wide <- make_foc_fails()	

## getting this error is OK; it just means there were no focal failures
#  Error in enc2utf8(col_names(col_labels, sep = sep)) : 
#   argument is not a character vector


#-----------
# make the nest Scoring Form
make_nest_scoring <- function(){
  # extract just the fields from 'nests' needed to export
  nests.sub=subset(screened_nests, select=c("species", "nest", "focal", "focal_fail", "fledged", "days_short_of_fledging", "active_last_day", "max_stage", "num_spp", "stg4_brood"))
  
  hep.wide <- alcatraz_hep %>% 
    arrange(species, date) %>% 
    select(date, species, nest, stg.age.chx) %>%
    unique() %>% 
    spread(date, stg.age.chx)
  names(hep.wide) <- gsub(paste(seas, "-", sep = ""),"",names(hep.wide))
  
  hep.wide1=full_join(hep.wide, nests.sub)
  return(hep.wide1)
}
hep.wide1 <- make_nest_scoring()


#-----------
# Number of stage 4 nests of each brood size
## gets written to final xls
stg4_wide=hep.wide1 %>%
  group_by(species, stg4_brood) %>%
  summarize(num_nests = length(nest)) %>% 
  filter(stg4_brood>0)%>% 
  mutate(stg4_brood = paste("BRD", stg4_brood, sep = "")) %>% 
  spread(stg4_brood, num_nests) 
stg4_wide[is.na(stg4_wide)] = 0



##----------
## replace all the NAs with blank to make the xls output tidier
hep.wide1[is.na(hep.wide1)] <- ""
focal_fail_dates_wide[is.na(focal_fail_dates_wide)] <- ""
## getting this error is OK; it just means there were no focal failures
# Error in focal_fail_dates_wide[is.na(focal_fail_dates_wide)] <- "" : 
# object 'focal_fail_dates_wide' not found
nest_num_stage[is.na(nest_num_stage)] <- ""
num_active_wide[is.na(num_active_wide)] <- ""
stg4_wide[is.na(stg4_wide)] <- ""



#################		RUN TO HERE FIRST		################

### look at numer of nests for each species to decide whether final xlsx should have spp lumped or in different sheets.
### then run export.hep()  and desired appender functions below
hep %>%
  group_by(species, nest) %>%
  select(species, nest) %>%
  unique() %>% 
  group_by(species) %>%
  summarise(num_nests = n()) %>% 
  data.frame()

### look at numer of multi-species nests to decide whether final xlsx should have sheet for those.
hep.wide1 %>% filter(num_spp>1) %>% nrow()

##-------------------------------------


# need to make all the tbls into dfs for write.xlsx  
hep.wide1 <- as.data.frame(hep.wide1)
peak_active <- as.data.frame(peak_active)
stg4_wide <- as.data.frame(stg4_wide)
nest_num_stage <- as.data.frame(nest_num_stage)
num_active_wide <- as.data.frame(num_active_wide)
#visits <- as.data.frame(visits) 
# set path for file to be written to
zfile <- paste("S:/Databases/HEP_screening/scoring/", paste(seas, col, sep="/"), "_scoring.xlsx", sep="")



### load these funtions to write the scoring file with the base sheets (export.hep()) and then the appender functions
## the functions are actually called (executed) below
export.hep=function(seas, col){
  write.xlsx(peak_active, file=zfile, sheetName="peak_active", append=TRUE, row.names=FALSE)
  write.xlsx(stg4_wide, file=zfile, sheetName="stg4", append=TRUE, row.names=FALSE)
  write.xlsx(nest_num_stage, file=zfile, sheetName="nest_num_stage", append=TRUE, row.names=FALSE)
  write.xlsx(num_active_wide, file=zfile, sheetName="num_active", append=TRUE, row.names=FALSE)
#  write.xlsx(visits, file=zfile, sheetName="visits", append=TRUE, row.names=FALSE)
}

append.all.spp=function(seas, col){
  write.xlsx(hep.wide1, file=zfile, sheetName="nests", row.names=FALSE)
}
append.bcnh=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="BCNH",], file=zfile, sheetName="BCNH", append=TRUE, row.names=FALSE)
}
append.caeg=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="CAEG",], file=zfile, sheetName="CAEG", append=TRUE, row.names=FALSE)
}
append.greg=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="GREG",], file=zfile, sheetName="GREG", append=TRUE, row.names=FALSE)
}
append.sneg=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="SNEG",], file=zfile, sheetName="SNEG", append=TRUE, row.names=FALSE)
}
append.gbhe=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="GBHE",], file=zfile, sheetName="GBHE", append=TRUE, row.names=FALSE)
}
append.dcco=function(seas, col){
  write.xlsx(hep.wide1[hep.wide1$species=="DCCO",], file=zfile, sheetName="DCCO", append=TRUE, row.names=FALSE)
}
append.multi.spp=function(seas, col){ 
  write.xlsx(hep.wide1[hep.wide1$num_spp>1,], file=zfile, sheetName="multiSpp", append=TRUE, row.names=FALSE)
}
append.focfail=function(seas, col){
  focal_fail_dates_wide <- as.data.frame(focal_fail_dates_wide)
  write.xlsx(focal_fail_dates_wide, file=zfile, sheetName="focal_fail_dates", append=TRUE, row.names=FALSE)
}

## now export the base scoring file
export.hep(seas, col)
## and append the desired nest sheets to it
append.all.spp(seas, col)
append.bcnh(seas, col)
append.caeg(seas, col)
append.greg(seas, col)
append.sneg(seas, col)
append.gbhe(seas, col)
append.dcco(seas, col)
append.multi.spp(seas, col)
append.focfail(seas, col)


## YOU SHOULD BE DONE HERE








############################################################################################################

### these generally won't be needed, but these are some functions for appending single worksheets to a file that already exists
## you'll have to delete that sheet if it already exists in the file
append.visits=function(seas, col){
  visits <- as.data.frame(visits)
  write.xlsx(visits, file=zfile, sheetName="visits", append=TRUE, row.names=FALSE)
}
append.visits(seas, col)

append.focfail=function(seas, col){
  focal_fail_dates_wide <- as.data.frame(focal_fail_dates_wide)
  write.xlsx(focal_fail_dates_wide, file=zfile, sheetName="focal_fail_dates", append=TRUE, row.names=FALSE)
}
append.focfail(seas, col)

append.num.stage=function(seas, col){
  nest_num_stage <- as.data.frame(nest_num_stage)
  write.xlsx(nest_num_stage, file=zfile, sheetName="nest_num_stage", append=TRUE, row.names=FALSE)
}
append.num.stage(seas, col)


########